version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
bountiful = true
azurelib = true
everycomp = true
farmersdelight = true
spelunkery = true
mutantmonsters = true
coppertunity = true
extendedcopper = true
villagerprofessionsplus = true
storagedrawers = true
betternether = true
hamsters = true
morefrogs = true
galosphere = true
ecologics = true
friendsandfoes = true
gravity_changer = true
natures_spirit = true
copycats = false
spellbound = true
sprout = true
dramaticdoors = true
verdantvibes = true
sootychimneys = true
railways = true
guardianexpansion = true
additionaladditions = true
handcrafted = true
snowrealmagic = true
srias_flowers = true
charm = true
exposure = true
naturalist = true
ironchests = true
endersdelight = true
supplementaries = true
many_flowers = true
botania = true
culturaldelights = true
create = true
yungscavebiomes = true
missingwilds = true
minecraft = true
farmersrespite = true
withered-bone-meal = true
kawaflora = true
natures_delight = true
snifferplus = true
underground_jungle = true
createaddition = true
twilightforest = true
sliceanddice = true
creeperoverhaul = true
numismatic-overhaul = true
flower_power = true
amyshield = true
illagerinvasion = true
bushierflowers = true
more_spawners = true
petal = true
overweight_farming = true
froglegs = true
morelapis = true
ribbits = true
dungeonnowloading = true
brewinandchewin = true
undergroundmod = true
betterend = true
automobility = true
amethyst_update = true
legacies_and_legends = true
aquamirae = true
delightful = true
enhancedcelestials = true
snowyspirit = true
nethersdelight = true
origins = true
goblinmines_minecart_tweaks = true
bellsandwhistles = true
milk = true
amendments = true
hexed = true
sophisticatedbackpacks = true
amethyst_imbuement = true
glow_ink_plus = true
corndelight = true
agricraft = true
cratedelight = true
caligo = true
coffins = true
suppsquared = true
amethystgravity = true
bountifulfares = true
interiors = true
beaconoverhaul = true
fwaystones = true
lootr = true
iceandfire = true
createdeco = true
regions_unexplored = true
qu-enchantments = true
betterarcheology = true
appbot = true
malum = true
ae2 = true
endermanoverhaul = true
immersive_weathering = true
bosses_of_mass_destruction = true
decorative_blocks = true
create_deepslate_processing = true
crittersandcompanions = true
moyai = true
villagersplus = true
spider_caves = true
ad_astra = true
hearth_and_home = true
oreganized = true
