[behaviour]
	#This section determines the behaviour of the Weeping Angels.
	#Range for player visibility check.
	#Range: 1 ~ 100
	stalk_range = 65
	#Allow angels to break light-emitting blocks?
	block_breaking = true

[damage]
	#Type of hurt inflicted by angels.
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "GENERATOR"

[teleporting]
	#Range for teleportation.
	#Range: > 1
	teleport_range = 1000
	#Allow teleporting across dimensions?
	interdimensional_teleporting = false
	#Allow Angel theft?
	angel_theft = true
	#Chance of teleportation occurring.
	#Range: 1 ~ 100
	teleport_chance = 100
	#Dimensions where teleportation is banned.
	banned_dimensions = []
